server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/harmoni
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ecoharmonypark219@gmail.com
spring.mail.password=swnokycntrnwfzwq
spring.mail.transport.protocol=smtp
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true
spring.mail.from.email=<gmail-username@gmail.com>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


