FROM node:18-alpine

WORKDIR /app

# Argumento de build
ARG VITE_BACKEND_URL=http://backend:8080

# Variable de entorno
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]