name: HarmoniApp

services:
  dbHarmoniApp:
    container_name: dbHarmoniApp
    image: postgres:latest
    volumes:
      - dbHarmoniApp:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: harmoni
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      dbHarmoniApp:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"  # Puerto por defecto de Vite
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: on-failure
    depends_on:
      - backend

volumes:
  dbHarmoniApp: