name: HarmoniApp

services:
  dbHarmoniApp:
    container_name: dbHarmoniApp
    image: postgres:latest
    volumes:
      - dbHarmoniApp:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: harmoni
      TZ: America/Argentina/Buenos_Aires   # ✅ Zona horaria correcta
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      dbHarmoniApp:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  dbHarmoniApp:
